### ISSUE TITLE
Only for bacteria?

### ISSUE THREAD

**Issue by LauraVP1994** [rrwick/Assembly-Dereplicator#2]
Dear,

Thank you for making this tool available, I was wondering whether the tool is only limited to bacterial genomes or can it also be used for animal, plant, fungi or viral genomes?

Thank you
Laura

**Comment by rrwick** [comment]
I've never tried it on anything but prokaryote genomes, but I don't see why it wouldn't work on eukaryote genomes as well. As long as your assemblies are in FASTA format ([with one of the normal file extensions](https://github.com/rrwick/Assembly-Dereplicator/blob/main/dereplicator.py#L164-L167)), it should be fine!

The `dereplicator.py` script uses Mash to get pairwise distances, and I'm not sure how computationally intensive that is for big genomes. You could make things faster by using a smaller Mash [sketch size](https://mash.readthedocs.io/en/latest/sketches.html#sketch-size), e.g. `--sketch_size 1000`.

Ryan
